# Generated by Django 4.2.7 on 2024-10-29 05:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("SWE", "Software Engineer"),
                            ("DE", "Data Engineer"),
                            ("DS", "Data Scientist"),
                            ("FE", "Frontend Engineer"),
                            ("BE", "Backend Engineer"),
                            ("FS", "Full Stack Engineer"),
                            ("ML", "Machine Learning Engineer"),
                            ("QA", "Quality Assurance Engineer"),
                        ],
                        default="SWE",
                        max_length=3,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Attendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_checked_in", models.BooleanField(default=False)),
                ("is_checked_out", models.BooleanField(default=False)),
                ("check_in", models.DateTimeField(auto_now_add=True)),
                ("check_out", models.DateTimeField(auto_now=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="attendance.employee",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_owner",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
